### ISSUE TITLE
make possible to netsetgo to connect to existent bridges

### ISSUE THREAD

**Issue by marcosps** [teddyking/netsetgo#1]
Currently lxc allows the newly created container to connect to an already created bridge, like lxcbr0 (lxc bridge) or virbr0 (created by libvirt).

instead of creating a new bridge and set all the iptables rules, netsetgo could have a new option to create the veth pair and connect to an existent bridge.

@teddyking do you think this is a nice idea? If yes, I can try to work on it !

**Comment by teddyking** [comment]
@marcosps I think that's a great idea! And PRs would be very welcome.

**Comment by marcosps** [comment]
Closing old bugs :)
