### ISSUE TITLE
netsetgo binary not working

### ISSUE THREAD

**Issue by allthingssecurity** [teddyking/netsetgo#5]
Running this binary netsetgo gives me the error
ERROR - operation not supported

Linux Kernel level  4.20.12
golang 1.10
OS : Ubuntu 18.10

Permissions on the file
-rwsr-xr-x 1 root root 2771952 May 24  2017 /usr/local/bin/netsetgo

WHat can be the possible reason.

**Comment by teddyking** [comment]
What user are you running the netsetgo binary as?
It will require root permissions to work properly.

**Comment by allthingssecurity** [comment]
Issue was with linux bridge. Worked it out. Thanks
